INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (31, 4, 'Technical Excellence', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (32, 4, 'Strategic Advicve', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (33, 4, 'Operational Excellence', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (34, 6, 'Optimum Equipment Effectiveness', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (35, 6, 'Output Effectiveness Evaluation', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (36, 6, 'Operational Equipment Efficiency', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (37, 6, 'Overall Equipment Effectiveness', 1, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (38, 6, 'Overly Elaborate Explanation', 0, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (39, 8, 'True', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (40, 8, 'False', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (55, 19, 'True', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (56, 19, 'False', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (70, 27, 'True', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (71, 27, 'False', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (82, 41, 'Communicate progress transparently and show milestones ahead', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (83, 41, 'Re-set expectations to align with realistic timelines', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (84, 41, 'Promise immediate results to ease tension', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (85, 41, 'Avoid contact until results appear', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (90, 35, 'Be prepared, make sure there are no inconsistencies in your materials, and that the examples  and data you use are relevant.', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (91, 35, ' Having a clear intention - not knowing where you want to go with your discussion is a disaster.', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (92, 35, 'Show off your knowledge often to establish authority', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (93, 35, 'Be honest, and say “I don’t know” when appropriate', 1, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (94, 35, 'Practice leads to competence, competence leads to confidence.', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (95, 38, 'Say what you’ll do, and do what you say', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (96, 38, 'Always pre-present to key stakeholders', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (97, 38, 'Avoid escalation and never admit fault', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (98, 38, 'Reconfirm events and solve problems quickly', 1, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (99, 38, 'Use excuses when delays occur', 0, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (104, 45, 'Count Not Working / Count Present', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (105, 45, 'Count Working / Total Count', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (106, 45, 'Productive Time / Available Time', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (107, 45, 'Total Output / Total Time', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (108, 44, 'Sweat-shop environments: >75%', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (109, 44, 'Manufacturing: 45%-75%', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (110, 44, 'Service: 35%-65%', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (111, 44, 'Maintenance / Construction / O&G: 15%–40%', 1, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (112, 49, 'True', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (113, 49, 'False', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (114, 53, 'Recommend immediate 30% headcount reduction to match the 32% reading', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (115, 53, 'Explain that 32% falls within the typical 15%-40% range for maintenance/construction/oil & gas, but conduct a Wrench Time study to identify which delays are impactable', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (116, 53, 'Suggest switching to OEE measurement to get a higher-looking number', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (117, 53, 'Acknowledge the poor performance and recommend process outsourcing', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (118, 54, 'Produce and deliver products and services', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (119, 54, 'Manage improvement and change', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (120, 54, 'Market and sell', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (121, 54, 'Invoice and service customers', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (122, 55, 'A Process Group can contain multiple Functions', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (123, 55, 'A Function (e.g., Sales) can contain multiple Process Groups (e.g., Delivery)', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (124, 55, 'A Process can be broken down into Activities/Tasks', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (125, 55, 'Activities are the lowest level of granularity possible in the Work Taxonomy', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (126, 56, 'True', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (127, 56, 'False', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (128, 61, 'Use actual life-sized copies of documents and computer interface screenshots pasted directly on the brown paper', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (129, 61, 'Always include every page of multi-page documents to maintain complete documentation', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (130, 61, 'Write document names in large letters using marker pen for readability during presentations', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (131, 61, ' Use PostIt Notes for critiques so they can be grouped by affinity later', 1, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (132, 61, 'Verify that documents are "live" (current/recently used) and have history, not magically produced after your arrival', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (133, 61, 'Use a single sheet of brown paper to keep the presentation compact and professional', 0, 6);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (134, 63, 'Value Adding (VA); because it produces a necessary output', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (135, 63, 'Partially Value Adding (PVA); because some portions add value', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (136, 63, 'Non-Value Adding (NVA); specifically, duplication of data (Operation type)', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (137, 63, 'Non-Value Adding (NVA); specifically, multiple manual manipulations (Movement type)', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (138, 64, 'True', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (139, 64, 'False', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (140, 65, 'Feedback loops are used to measure how happy employees are with their work', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (141, 65, 'If you are unhappy with system outputs, you need feedback on performance to adjust inputs until you are happy with outputs', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (142, 65, 'Feedback loops are primarily used to communicate bad news to senior management', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (143, 65, 'Feedback loops eliminate the need for planning because real-time adjustments make plans obsolete', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (148, 68, 'True', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (149, 68, 'False', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (150, 69, 'Classroom theory training only', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (151, 69, 'Direct interventions in the workplace showing how to do the job properly', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (152, 69, 'Annual performance reviews only', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (153, 69, 'Assigning disciplinary actions to poor performers', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (154, 73, 'Organisation Development and Process Mapping', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (155, 73, 'Organisation Design (Procedural) and Organisation Development (Behavioural)', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (156, 73, 'Job Design and Centralisation', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (157, 73, 'Policy Deployment and Talent Management', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (158, 76, 'True', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (159, 76, 'False', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (160, 77, 'Improve customer satisfaction', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (161, 77, 'Increase bureaucracy', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (162, 77, 'Reduce hierarchical layers', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (163, 77, 'Increase span of control', 1, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (164, 77, 'Low risk of adverse side effects', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (165, 79, 'True', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (166, 79, 'False', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (167, 84, 'Check source and verify accuracy of data', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (168, 84, 'Aim for at least 30 measurements in any sample', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (169, 84, 'Identify and investigate outliers (>1.5 times IQR from quartiles)', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (170, 84, 'Accept all data regardless of inconsistencies', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (171, 84, 'Use Excel Descriptive Statistics to check for normality', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (172, 84, 'Always remove any data that doesn''t fit your hypothesis', 0, 6);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (173, 87, 'True', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (174, 87, 'False', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (175, 89, 'Direct payroll', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (176, 89, 'National insurance/government tax paid by employer', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (177, 89, 'Recruitment', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (178, 89, 'Office building rent', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (179, 89, 'Training', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (180, 89, 'Paid sick leave', 1, 6);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (181, 90, 'Extracting, Transforming, Loading (ETL)', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (182, 90, 'Sourcing, Organizing, Reporting', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (183, 90, 'Collecting, Cleaning, Visualizing', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (184, 90, 'Planning, Implementing, Monitoring', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (185, 93, 'Fixing null (missing) values', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (186, 93, 'Using raw data, not pre-existing reports', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (187, 93, 'Ensuring measurement methods are repeatable and reproducible', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (188, 93, 'Accepting all data regardless of inconsistencies', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (189, 93, 'Identifying and investigating outliers', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (190, 93, 'Using descriptive statistics to test for normality', 1, 6);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (191, 95, 'True', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (192, 95, 'False', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (193, 96, 'The lack of affordable BI tools', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (194, 96, 'The data that is NOT measured', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (195, 96, 'Poor data visualization techniques', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (196, 96, 'Insufficient IT infrastructure', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (197, 97, 'Speeds up report and chart preparation', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (198, 97, 'Builds a common data language', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (199, 97, 'Centralises data from disparate silos/systems to a single digital platform', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (200, 97, 'Eliminates all need for data governance', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (201, 97, 'Highlights current inefficiencies in business and data processes', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (202, 97, 'Establishes data foundations for more powerful BI', 1, 6);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (233, 13, 'Agreement to Proceed', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (234, 13, 'Reference letters', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (235, 13, 'PM Reports', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (236, 13, 'Close out reports', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (237, 13, 'Consultant Training', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (238, 13, 'Steps to Milestone document', 0, 6);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (239, 13, 'More work scope', 1, 7);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (240, 13, 'Client change requests', 1, 8);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (241, 13, 'Strategic Integration Meeting Map', 0, 9);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (256, 26, 'True', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (257, 26, 'False', 1, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (262, 24, 'Designing new strategy frameworks', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (263, 24, 'Better financial ratios', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (264, 24, 'People behaving differently', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (265, 24, 'Improved control systems', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (278, 25, 'Strategy', 0, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (279, 25, 'Structure', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (280, 25, 'Shared Values', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (281, 25, 'Skills', 1, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (282, 25, 'Systems', 0, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (283, 25, 'Staff', 1, 6);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (284, 25, 'Style', 1, 7);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (290, 10, 'Client Management', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (291, 10, 'People Management', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (292, 10, 'Change Management', 1, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (293, 10, 'Sales Management', 0, 4);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (294, 10, 'Project Management', 1, 5);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (299, 34, '(Credibility + Reliability + Intimacy) ÷ Self-Orientation', 1, 1);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (300, 34, '(Credibility + Intimacy) × Reliability × Self-Orientation', 0, 2);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (301, 34, '(Credibility × Reliability × Intimacy) ÷ Self-Orientation', 0, 3);
INSERT INTO answer_options (id, question_id, option_text, is_correct, order_index) VALUES (302, 34, '(Credibility × Intimacy) ÷ Reliability × Self-Orientation', 0, 4);
